### PR TITLE
Small program that tells you how hip D is

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
```
/tmp/dmd_runaa1jxb: error while loading shared libraries: libphobos2.so.0.67: cannot open shared object file: No such file or directory
```

mmmm....

**Comment by leandro-lucarella-sociomantic** [comment]
I would have expected that for libcurl, but not for libphobos2 :P

**Comment by MartinNowak** [comment]
Oh I see, that's because of pragma(lib, "phobos2"). Shared libraries take precedence over static libraries, "libphobos2.a" should work but only on POSIX. Then again shared libraries should work fine in travis-ci as well.

**Comment by leandro-lucarella-sociomantic** [comment]
I commented out the `pragma(lib, "phobos2")` and now it can't find references to curl...

**Comment by leandro-lucarella-sociomantic** [comment]
Thinks linking order situation is quite unfortunate... :S

**Comment by MartinNowak** [comment]
I know, but it will be fixed soon https://github.com/D-Programming-Language/phobos/pull/3009.
We can use specialized build commands in the test script.
`dmd -L-llibphobos2.a -L-lcurl -run d_is_like` should work.

**Comment by MartinNowak** [comment]
I'll merge this anyhow, meanwhile Vladimir fixed the YourCodeHere rotation.

**Pull request merged**
